In [1]:
import numpy as np
import jax
import jax.numpy as jnp
from tqdm import tqdm
import os
from lib.models.forward_model import UniformForward


In [2]:
rate_const = 1
S = 3
B = 2
D = 4
uni = UniformForward(S, rate_const)

rng = jax.random.PRNGKey(1008)
t_rng, sample_rng = jax.random.split(rng)
t = jax.random.uniform(t_rng, (B,))
qt0 = uni.transition(t)
qt0_y2x = jnp.transpose(qt0, (0, 2, 1))
print(qt0)
print(qt0)

print(qt0)

[[[0.3771065  0.31144676 0.31144676]
  [0.31144676 0.3771065  0.31144676]
  [0.31144676 0.31144676 0.3771065 ]]

 [[0.38507968 0.30746016 0.30746016]
  [0.30746016 0.38507968 0.30746016]
  [0.30746016 0.30746016 0.38507968]]]


In [ ]:
"""
The main bottleneck is the design of the conditional marginal parameterization, which requires non-trivial trade-offs between computational cost 
and flexibility of the architectures; score matching for general categorical discrete variables does not benefit from prior knowledge about ordinal 
discrete data; and finally unifying score matching between continu- ous and discrete spaces would be needed to handle data in mixed spaces
"""