In [42]:
import pandas as pd
import numpy as np

In [27]:
def pad_sequence(seq, max_length=48, pad_char='-'):
    return seq.ljust(max_length, pad_char)
char_to_index = {
    'A': 0, 'R': 1, 'N': 2, 'D': 3, 'C': 4, 'Q': 5, 'E': 6, 'G': 7, 'H': 8, 'I': 9,
    'L': 10, 'K': 11, 'M': 12, 'F': 13, 'P': 14, 'S': 15, 'T': 16, 'W': 17, 'Y': 18, 'V': 19,
    '-': 20  
}
def sequence_to_numbers(seq):
    return [char_to_index[char] for char in seq]
def numbers_to_sequence(seq):
    pass

df = pd.read_csv('lib/datasets/Protein_sequences/grampa.csv')
sequences = df['sequence']
seq = sequences[sequences.str.len().between(12, 48)]
seq = seq.drop_duplicates()

In [32]:
print(seq)
pad_seq = seq.apply(pad_sequence).reset_index(drop=True)
print(pad_seq)
num_seq = pad_seq.apply(sequence_to_numbers)
print(type(num_seq[0][0]))

print(num_seq)
print(num_seq[2])

0                          GLPRKILCAIAKKKGKCKGPLKLVCKC
1           GFGCPGDAYQCSEHCRALGGGRTGGYCAGPWYLGHPTCTCSF
7                        LVKDNPLDISPKQVQALCTDLVIRCMCCC
11                                       YPELQQDLIARLL
15               GVFTLIKGATQLIGKTLGKELGKTGLELMACKITEQC
                             ...                      
51282                   RCICTTRTCRFPYRRLGTCLFQNRVYTFCC
51295                          KKWKKFIKKIGIGAVLTTPGAKK
51298    GIINTLQKYYCRVRGGRCAVLSCLPKEEQICKCSTRGRKCCRRKK
51330                    KLWKLFKKIGIGAVLKVLTTGLPALKLTK
51338                                     LNKGAILKHIIK
Name: sequence, Length: 5235, dtype: object
0       GLPRKILCAIAKKKGKCKGPLKLVCKC---------------------
1       GFGCPGDAYQCSEHCRALGGGRTGGYCAGPWYLGHPTCTCSF------
2       LVKDNPLDISPKQVQALCTDLVIRCMCCC-------------------
3       YPELQQDLIARLL-----------------------------------
4       GVFTLIKGATQLIGKTLGKELGKTGLELMACKITEQC-----------
                              ...                       
5230    R

In [43]:
arr_str = np.stack(pad_seq.values, 0)
print(arr_str, type(arr_str), arr_str.shape)

['GLPRKILCAIAKKKGKCKGPLKLVCKC---------------------'
 'GFGCPGDAYQCSEHCRALGGGRTGGYCAGPWYLGHPTCTCSF------'
 'LVKDNPLDISPKQVQALCTDLVIRCMCCC-------------------' ...
 'GIINTLQKYYCRVRGGRCAVLSCLPKEEQICKCSTRGRKCCRRKK---'
 'KLWKLFKKIGIGAVLKVLTTGLPALKLTK-------------------'
 'LNKGAILKHIIK------------------------------------'] <class 'numpy.ndarray'> (5235,)


In [45]:

print(num_seq)
arr = np.stack(num_seq.values, 0)
print(arr, type(arr), arr.shape)

np.save('lib/datasets/Protein_sequences/grampa_numarr.npy', arr)

0       [7, 10, 14, 1, 11, 9, 10, 4, 0, 9, 0, 11, 11, ...
1       [7, 13, 7, 4, 14, 7, 3, 0, 18, 5, 4, 15, 6, 8,...
2       [10, 19, 11, 3, 2, 14, 10, 3, 9, 15, 14, 11, 5...
3       [18, 14, 6, 10, 5, 5, 3, 10, 9, 0, 1, 10, 10, ...
4       [7, 19, 13, 16, 10, 9, 11, 7, 0, 16, 5, 10, 9,...
                              ...                        
5230    [1, 4, 9, 4, 16, 16, 1, 16, 4, 1, 13, 14, 18, ...
5231    [11, 11, 17, 11, 11, 13, 9, 11, 11, 9, 7, 9, 7...
5232    [7, 9, 9, 2, 16, 10, 5, 11, 18, 18, 4, 1, 19, ...
5233    [11, 10, 17, 11, 10, 13, 11, 11, 9, 7, 9, 7, 0...
5234    [10, 2, 11, 7, 0, 9, 10, 11, 8, 9, 9, 11, 20, ...
Name: sequence, Length: 5235, dtype: object
[[ 7 10 14 ... 20 20 20]
 [ 7 13  7 ... 20 20 20]
 [10 19 11 ... 20 20 20]
 ...
 [ 7  9  9 ... 20 20 20]
 [11 10 17 ... 20 20 20]
 [10  2 11 ... 20 20 20]] <class 'numpy.ndarray'> (5235, 48)


In [33]:
# Angenommen, 'series' ist Ihre Pandas Series
num_seq.to_csv('lib/datasets/Protein_sequences/grampa_num.csv', header=True, index=False)

pad_seq.to_csv('lib/datasets/Protein_sequences/grampa_pad.csv', header=True, index=False)

In [30]:
df_num = pd.read_csv('lib/datasets/Protein_sequences/grampa_num.csv')['sequence']

print(df_num, type(df_num[0]))
print(len(df_num[0]))

0       [7, 10, 14, 1, 11, 9, 10, 4, 0, 9, 0, 11, 11, ...
1       [7, 13, 7, 4, 14, 7, 3, 0, 18, 5, 4, 15, 6, 8,...
2       [10, 19, 11, 3, 2, 14, 10, 3, 9, 15, 14, 11, 5...
3       [18, 14, 6, 10, 5, 5, 3, 10, 9, 0, 1, 10, 10, ...
4       [7, 19, 13, 16, 10, 9, 11, 7, 0, 16, 5, 10, 9,...
                              ...                        
5230    [1, 4, 9, 4, 16, 16, 1, 16, 4, 1, 13, 14, 18, ...
5231    [11, 11, 17, 11, 11, 13, 9, 11, 11, 9, 7, 9, 7...
5232    [7, 9, 9, 2, 16, 10, 5, 11, 18, 18, 4, 1, 19, ...
5233    [11, 10, 17, 11, 10, 13, 11, 11, 9, 7, 9, 7, 0...
5234    [10, 2, 11, 7, 0, 9, 10, 11, 8, 9, 9, 11, 20, ...
Name: sequence, Length: 5235, dtype: object <class 'str'>
180


In [36]:
df_pad= pd.read_csv('lib/datasets/Protein_sequences/grampa_pad.csv')['sequence']
print(df_pad, type(df_pad[0]))
print(len(df_pad[0]))
num_seq_df = df_pad.apply(sequence_to_numbers)
print(num_seq_df, type(num_seq_df[0]), len(num_seq_df[0]))

0       GLPRKILCAIAKKKGKCKGPLKLVCKC---------------------
1       GFGCPGDAYQCSEHCRALGGGRTGGYCAGPWYLGHPTCTCSF------
2       LVKDNPLDISPKQVQALCTDLVIRCMCCC-------------------
3       YPELQQDLIARLL-----------------------------------
4       GVFTLIKGATQLIGKTLGKELGKTGLELMACKITEQC-----------
                              ...                       
5230    RCICTTRTCRFPYRRLGTCLFQNRVYTFCC------------------
5231    KKWKKFIKKIGIGAVLTTPGAKK-------------------------
5232    GIINTLQKYYCRVRGGRCAVLSCLPKEEQICKCSTRGRKCCRRKK---
5233    KLWKLFKKIGIGAVLKVLTTGLPALKLTK-------------------
5234    LNKGAILKHIIK------------------------------------
Name: sequence, Length: 5235, dtype: object <class 'str'>
48
0       [7, 10, 14, 1, 11, 9, 10, 4, 0, 9, 0, 11, 11, ...
1       [7, 13, 7, 4, 14, 7, 3, 0, 18, 5, 4, 15, 6, 8,...
2       [10, 19, 11, 3, 2, 14, 10, 3, 9, 15, 14, 11, 5...
3       [18, 14, 6, 10, 5, 5, 3, 10, 9, 0, 1, 10, 10, ...
4       [7, 19, 13, 16, 10, 9, 11, 7, 0, 16, 5, 10, 9,...
                      

In [ ]:
"""Ja das padden soll keinen Einfluss auf Entscheidungen des modells haben.

also mein vorgehen ist jetzt insgesamt bisher:
Daten lesen aus csv, padden zu länge 48, Buchstaben umwandeln zu Zahlen, dann daten ins model dort one_hot kodieren, aber sollte ich dann die gepaddeten stellen maskieren? die antwort ist sehr entscheidend für mich.

falls ich das maskiere, ist dann automatisch an diesen stellen der output, also die logits des neuronalen netzes -inf? oder was macht das masking ?
also ich berechne derzeit so den loss nach der prediction:
ich müsste ja sonst bevor ich die logits berechne an den gepaddeten stellen auch noch etwas machen? die logits haben den shape B,D, S. Außerdem müssen
        logits = model(xt, ts)  # B, D, S <10 sek
            x0_onehot = F.one_hot(minibatch.long(), self.cfg.data.S)
            ll = F.log_softmax(logits, dim=-1)
            loss = -torch.sum(ll * x0_onehot, dim=-1) * self.cfg.loss.ce_coeff
"""