In [5]:
import jax.numpy as jnp
import torch
import jax.random as jrandom

In [26]:
key = jrandom.PRNGKey(0)
xt = jrandom.uniform(key, (4, 3, 6))

print()
qt = jnp.expand_dims(jnp.arange(xt.shape[0]), tuple(range(1, xt.ndim)))
print(qt, qt.shape)

print(jnp.expand_dims(xt, axis=list(range(1, 4))).shape)
print(xt,jnp.expand_dims(xt, axis=list(range(1, 4))))


[[[0]]

 [[1]]

 [[2]]

 [[3]]] (4, 1, 1)
(4, 1, 1, 1, 3, 6)
[[[0.12073267 0.44929314 0.00260282 0.68199027 0.78009653 0.29813564]
  [0.70047235 0.8794887  0.6556964  0.00482321 0.41882515 0.48042595]
  [0.29205096 0.21646559 0.30872035 0.2548281  0.82435906 0.08740699]]

 [[0.91948986 0.38084304 0.08800554 0.39442313 0.67352223 0.28541255]
  [0.12428308 0.7304572  0.78445756 0.5880513  0.8471339  0.30039668]
  [0.60476243 0.4053675  0.4872228  0.8548782  0.9898492  0.55292404]]

 [[0.8253424  0.35411286 0.58544815 0.19673419 0.20969248 0.5978054 ]
  [0.69242346 0.49220645 0.9539496  0.6282892  0.35808563 0.05629992]
  [0.20315218 0.934389   0.49111092 0.95124125 0.1456021  0.2505288 ]]

 [[0.7395247  0.2631067  0.65211105 0.7451854  0.22367406 0.63648343]
  [0.66445124 0.03686202 0.9788079  0.6174903  0.814903   0.43530595]
  [0.4031955  0.17577243 0.4823358  0.3663218  0.90545917 0.31258512]]] [[[[[[0.12073267 0.44929314 0.00260282 0.68199027 0.78009653
      0.29813564]
     [0.700

In [27]:
def expand_dims(x, axis):
    for i in axis:
        x = x.unsqueeze(i)
    return x

In [32]:


# Schritt 2: Erzeugen Sie qt
xt = torch.rand(4, 3, 6)
print(expand_dims(torch.arange(xt.shape[0]), tuple(range(1, xt.ndim))).shape)
print(expand_dims(xt, list(range(1, 4))).shape)
qt_expanded = torch.arange(xt.shape[0]).reshape(tuple([-1] + [1]*(xt.ndim-1)))
#print(torch.arange(xt.shape[0]).expand(*(range(1, xt.ndim))))
print(qt_expanded)
print(qt_expanded.shape)

# Verwenden Sie die `reshape` Methode mit den vorher definierten Größen
result = xt.reshape(*[xt.shape[0]] + [1 for _ in range(1, xt.ndim)] + list(xt.shape[1:]))
print(result.shape)
print(xt, result)

torch.Size([4, 1, 1])
torch.Size([4, 1, 1, 1, 3, 6])
tensor([[[0]],

        [[1]],

        [[2]],

        [[3]]])
torch.Size([4, 1, 1])
torch.Size([4, 1, 1, 3, 6])
tensor([[[0.2493, 0.5496, 0.3046, 0.8310, 0.4288, 0.9275],
         [0.8076, 0.5148, 0.3006, 0.0286, 0.7578, 0.5786],
         [0.7252, 0.3524, 0.9219, 0.1451, 0.3496, 0.3882]],

        [[0.7397, 0.6084, 0.2809, 0.9216, 0.8382, 0.4439],
         [0.4445, 0.7117, 0.5543, 0.8372, 0.5011, 0.0597],
         [0.1054, 0.5696, 0.9440, 0.0075, 0.4481, 0.0983]],

        [[0.1586, 0.3107, 0.8893, 0.3812, 0.6998, 0.7501],
         [0.4207, 0.7099, 0.8185, 0.9781, 0.4887, 0.6037],
         [0.0728, 0.6709, 0.1278, 0.7500, 0.3423, 0.1373]],

        [[0.6853, 0.0884, 0.4980, 0.8625, 0.1186, 0.3952],
         [0.9933, 0.0155, 0.1585, 0.6537, 0.9630, 0.6772],
         [0.3897, 0.0480, 0.7935, 0.7779, 0.2553, 0.1746]]]) tensor([[[[[0.2493, 0.5496, 0.3046, 0.8310, 0.4288, 0.9275],
           [0.8076, 0.5148, 0.3006, 0.0286, 0.7578, 0.57